// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace dotnetconsulting.UserManagement.Logic.EntityFramework
{
    public partial class Role
    {
        public Role()
        {
            Users = new HashSet<User>();
            UserRoles = new HashSet<UserRole>();
        }

        public int ObjectId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<User> Users { get; set; }
        internal virtual ICollection<UserRole> UserRoles { get; set; }
    }
}