// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace dotnetconsulting.UserManagement.Logic.EntityFramework
{
    public partial class UserPlantCode
    {
        public int ObjectId { get; set; }
        public int UserObjectId { get; set; }
        public string Code { get; set; }

        public virtual User UserObject { get; set; }
    }
}